#:kivy 2.0

<LoginScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        Button:
            text: "Open Home Screen"
            size_hint: 0.5, 0.2
            on_press: root.switch_to_home()

<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        Button:
            text: "Open Login Screen"
            size_hint: 0.2, 0.2
            on_press: root.switch_to_login()
